version: '3.1'

services: 
    database:
        image: postgres:12.1-alpine
        restart: always
        environment: 
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_DB: ${DB_NAME}
        ports: 
            - ${DB_LISTEN_PORT_OUT}:${DB_PORT}
        volumes: 
            - postgres:/var/lib/postgresql/data
            - ${DB_VOLUME_PATH}:/var/lib/postgresql/data

volumes:
    postgres: