version: "3.7"
services:
    web:
        container_name: web
        restart: always
        image: ludwin/web-granja
        ports:
            - 8081:80
        networks:
            - granjanet
        depends_on:
            - api

    api:
        container_name: api
        restart: always
        image: ludwin/api-granja
        ports:
            - ${SERVER_PORT}:${SERVER_PORT}
        command: npm run start:dev
        env_file:
            - .env
        networks:
            - granjanet
        depends_on:
            - database

    database:
        container_name: db
        image: postgres:17.5-alpine
        restart: always
        env_file:
            - .env
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_DB: ${DB_NAME}
            TZ: 'America/Guatemala'
        ports:
            - ${DB_LISTEN_PORT_OUT}:${DB_PORT}
        volumes:
            - ./tools/postgres/data:/var/lib/postgresql/data
            - ./tools/postgres/backups:/backups
        networks:
            - granjanet
networks:
  granjanet: